# Generated by Django 5.0.6 on 2024-07-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_comment_reply_to_post_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
