# Generated by Django 5.0.6 on 2024-08-01 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_comment_reply_to_alter_post_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archiver', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_post', to='network.post')),
            ],
        ),
    ]
