# Generated by Django 5.0.6 on 2024-08-01 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archived',
            name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archived_location', to='network.archive'),
        ),
    ]
