# Generated by Django 5.0.6 on 2024-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_archive_archived_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived',
            name='archive',
        ),
        migrations.AddField(
            model_name='archived',
            name='archive',
            field=models.ManyToManyField(related_name='archived_location', to='network.archive'),
        ),
    ]
