# Generated by Django 5.0.6 on 2024-08-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_archived_archive_archived_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archived_post', to='network.post'),
        ),
    ]
