# Generated by Django 5.0.6 on 2024-08-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_archived_archive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='archive',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_archive'),
        ),
        migrations.AddConstraint(
            model_name='archived',
            constraint=models.UniqueConstraint(fields=('post', 'archiver'), name='unique_archived'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('commenter', 'time', 'content'), name='unique_comment'),
        ),
        migrations.AddConstraint(
            model_name='followship',
            constraint=models.UniqueConstraint(fields=('follower', 'followed'), name='unique_followship'),
        ),
        migrations.AddConstraint(
            model_name='likeship',
            constraint=models.UniqueConstraint(fields=('post', 'liker'), name='unique_likeship'),
        ),
        migrations.AddConstraint(
            model_name='likeship_comment',
            constraint=models.UniqueConstraint(fields=('comment', 'liker'), name='unique_likeship_comment'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('poster', 'time', 'content'), name='unique_post'),
        ),
    ]
