# Generated by Django 5.0.6 on 2024-08-02 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_archive_unique_archive_archived_unique_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('self_intro', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
