# Generated by Django 5.0.6 on 2024-08-03 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
