# Generated by Django 5.0.6 on 2024-08-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_alter_comment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, default='empty', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reply', to='network.post'),
        ),
    ]
