# Generated by Django 5.0.6 on 2024-08-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_comment_is_reply_post_is_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alias',
            field=models.CharField(max_length=20),
        ),
    ]
