# Generated by Django 5.0.6 on 2024-07-25 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_followship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Likeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
