# Generated by Django 5.0.6 on 2024-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='activity',
            field=models.BooleanField(default=True),
        ),
    ]
