# Generated by Django 5.0.6 on 2024-07-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
