# Generated by Django 5.0.6 on 2024-07-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_user_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='winner',
        ),
    ]
