# Generated by Django 5.0.6 on 2024-07-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_user_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
