# Generated by Django 5.0.6 on 2024-07-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Toys', 'Toys'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Electronics', 'Electronics'), (models.CharField(), 'Custom')], max_length=20, null=True),
        ),
    ]
