# Generated by Django 5.0.6 on 2024-07-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_listing_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
